# #!/bin/bash
# #NOTE: DO NOT EDIT THIS FILE-- MAY RESULT IN INCOMPLETE SUBMISSIONS
# set -euo pipefail

# CODE=(
# 	"cs231n/classifiers/k_nearest_neighbor.py"
# 	"cs231n/classifiers/linear_classifier.py"
# 	"cs231n/classifiers/softmax.py"
# 	"cs231n/classifiers/fc_net.py"
# 	"cs231n/optim.py"
# 	"cs231n/solver.py"
# 	"cs231n/layers.py"
# )

# # these notebooks should ideally
# # be in order of questions so
# # that the generated pdf is
# # in order of questions
# NOTEBOOKS=(
# 	"knn.ipynb"
# 	"softmax.ipynb"
# 	"two_layer_net.ipynb"
# 	"features.ipynb"
# 	"FullyConnectedNets.ipynb"
# )

# FILES=( "${CODE[@]}" "${NOTEBOOKS[@]}" )

# LOCAL_DIR=`pwd`
# ASSIGNMENT_NO=1
# ZIP_FILENAME="a1_code_submission.zip"
# PDF_FILENAME="a1_inline_submission.pdf"

# C_R="\e[31m"
# C_G="\e[32m"
# C_BLD="\e[1m"
# C_E="\e[0m"

# for FILE in "${FILES[@]}"
# do
# 	if [ ! -f ${FILE} ]; then
# 		echo -e "${C_R}Required file ${FILE} not found, Exiting.${C_E}"
# 		exit 0
# 	fi
# done

# echo -e "### Zipping file ###"
# rm -f ${ZIP_FILENAME}
# zip -q "${ZIP_FILENAME}" -r ${NOTEBOOKS[@]} $(find . -name "*.py") "cs231n/saved" -x "makepdf.py"

# echo -e "### Creating PDFs ###"
# python makepdf.py --notebooks "${NOTEBOOKS[@]}" --pdf_filename "${PDF_FILENAME}"

# echo -e "### Done! Please submit ${ZIP_FILENAME} and ${PDF_FILENAME} to Gradescope. ###"


# %cd drive/My\ Drive
# %cd $FOLDERNAME
# !sudo apt-get install texlive-xetex texlive-fonts-recommended texlive-plain-generic texlive-latex-extra pandoc --fix-missing
# !pip install PyPDF2
# !bash collectSubmission.sh



#!/usr/bin/env bash
set -euo pipefail

CODE=(
  "cs231n/classifiers/k_nearest_neighbor.py"
  "cs231n/classifiers/linear_classifier.py"
  "cs231n/classifiers/softmax.py"
  "cs231n/classifiers/fc_net.py"
  "cs231n/optim.py"
  "cs231n/solver.py"
  "cs231n/layers.py"
)
NOTEBOOKS=(
  "knn.ipynb"
  "softmax.ipynb"
  "two_layer_net.ipynb"
  "features.ipynb"
  "FullyConnectedNets.ipynb"
)
ZIP_FILENAME="a1_code_submission.zip"
PDF_FILENAME="a1_inline_submission.pdf"
OUT_DIR="pdf_build"

PYTHON_BIN="${PYTHON_BIN:-python}"
if ${PYTHON_BIN} - <<'PY' >/dev/null 2>&1
import sys, pkgutil
mods = ["nbconvert","jupyter","PyPDF2"]
sys.exit(0 if all(pkgutil.find_loader(m) for m in mods) else 1)
PY
then
  :
else
  echo "[setup] Run in your venv:"
  echo "  pip install nbconvert jupyter PyPDF2"
  echo "If no browser is installed for webpdf, also:"
  echo "  pip install pyppeteer"
  echo '  python -c "import pyppeteer; import asyncio; asyncio.get_event_loop().run_until_complete(pyppeteer.chromium_downloader.download_chromium())"'
  exit 1
fi

FILES=( "${CODE[@]}" "${NOTEBOOKS[@]}" )
for FILE in "${FILES[@]}"; do
  if [ ! -f "${FILE}" ]; then
    echo "[error] Required file ${FILE} not found"
    exit 1
  fi
done

echo "### Zipping source ###"
rm -f "${ZIP_FILENAME}"

zip -q "${ZIP_FILENAME}" -r "${NOTEBOOKS[@]}" $(find . -name "*.py") "cs231n/saved" -x "makepdf_vscode.py" || true

echo "### Exporting notebooks to PDF (webpdf) ###"
mkdir -p "${OUT_DIR}"
for nb in "${NOTEBOOKS[@]}"; do
  stem="$(basename "${nb}" .ipynb)"
  echo " - ${nb} -> ${OUT_DIR}/${stem}.pdf"
  ${PYTHON_BIN} -m jupyter nbconvert \
    --to webpdf \
    --no-input \
    --output "${stem}" \
    "${nb}"
  mv "${stem}.pdf" "${OUT_DIR}/${stem}.pdf"
done

echo "### Merging PDFs ###"
pdf_args=()
for nb in "${NOTEBOOKS[@]}"; do
  stem="$(basename "${nb}" .ipynb)"
  pdf_args+=("${OUT_DIR}/${stem}.pdf")
done

${PYTHON_BIN} - "$PDF_FILENAME" "${pdf_args[@]}" <<'PY'
import sys
from PyPDF2 import PdfMerger
merged = sys.argv[1]
pdfs = sys.argv[2:]
m = PdfMerger()
for p in pdfs:
    m.append(p)
m.write(merged); m.close()
print(f"[done] Merged -> {merged}")
PY

echo "### Done! Submit ${ZIP_FILENAME} and ${PDF_FILENAME} ###"
